apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-deploy
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "main"
    - name: IMAGE
      type: string
      description: image to be build from the code
    - name: Dockerfile
      type: string
      description: image to be build from the code
      default: "./Dockerfile"
    - name: skip_push
      type: string
      description: whether to skip to push or not
      default: "true"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: ""
        - name: revision
          value: $(params.git-revision)
    - name: apply-manifest
      taskRef:
        name: apply-manifest
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - clone-repo
