apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mkspipelines.mkscontroller.example.mks
spec:
  group: mkscontroller.example.mks
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tasks:
                  type: object
                  properties:
                    name:
                      type: string
                    taskRef:
                      type: object
                      properties:
                        name:
                          type: string

  names:
    kind: MksPipeline
    plural: mkspipelines
  scope: Namespaced
