# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2022 Satyam Bhardwaj <sabhardw@redhat.com>
# SPDX-FileCopyrightText: 2022 Utkarsh Chaurasia <uchauras@redhat.com>
# SPDX-FileCopyrightText: 2022 Avinal Kumar <avinkuma@redhat.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mks-server-clusterRole
  labels:
    app.kubernetes.io/instance: mks-server-clusterRole
rules:
  - apiGroups: [""]
    # Controller needs to watch Pods created by TaskRuns to see them progress.
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
    # Controller needs cluster access to all of the CRDs that it is responsible for
    # managing.
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "clustertasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources", "conditions", "runs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns/finalizers", "pipelineruns/finalizers", "runs/finalizers"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["tasks/status", "clustertasks/status", "taskruns/status", "pipelines/status", "pipelineruns/status", "pipelineresources/status", "runs/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["mkscontroller.example.mks"]
    # Controller needs to watch Pods created by TaskRuns to see them progress.
    resources: ["mkstasks", "mkstaskruns", "mkspipelineruns"]
    verbs: ["get", "list", "create", "update", "delete", "watch" ]