# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2022 Satyam Bhardwaj <sabhardw@redhat.com>
# SPDX-FileCopyrightText: 2022 Utkarsh Chaurasia <uchauras@redhat.com>
# SPDX-FileCopyrightText: 2022 Avinal Kumar <avinkuma@redhat.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: run-test-run-
  namespace: mks
spec:
  params:
  - name: git-revision
    value: main
  - name: git-url
    value: https://github.com/MiniTeks/mks-server
  - name: package
    value: .
  - name: packages
    value: ./...
  - name: version
    value: 1.17.6
  pipelineRef:
    name: run-test
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: test-source-pvc
status: {}
